[package]
name = "opensim-networking"
version = "0.1.0"
authors = ["Leo Schwarz <mail@leoschwarz.com>"]

[dependencies]
bitflags = "1.0"
byteorder = "1.0"
derive-error-chain = "0.11.0"
error-chain = "0.11.0"
futures = "0.1.10"
mio = "0.6"
nalgebra = "0.10.1"
regex = "0.2.2"
reqwest = "0.7.3"
rust-crypto = "0.2.36"
time = "0.1.36"
ttl_cache = "0.2.1"
url = "1.2"
uuid = {version = "0.5.1", features = ["use_std"]}
xmlrpc = "0.7.0"

[dev-dependencies]
toml = "0.3"

