[package]
name = "opensim_messages"
version = "0.2.0"
authors = ["Leo Schwarz <mail@leoschwarz.com>", "Dave Richardson <dsrich@hotmail.com>"]
license = "GPL-3.0"

[dependencies]
arrayvec = "*"
byteorder = "*"
failure = "*"
opensim_types = { path = "../opensim_types" }
