[package]
name = "opensim_messages"
version = "0.1.0"
authors = ["Leo Schwarz <mail@leoschwarz.com>"]
license = "GPL-3.0"

[dependencies]
arrayvec = "0.4.2"
byteorder = "1.0"
error-chain = "0.11.0"
derive-error-chain = "0.11.0"
opensim_types = { path = "../opensim_types" }
